apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-docker-test
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      bb: web
  template:
    metadata:
      labels:
        bb: web
    spec:
      containers:
      - name: python-todo
        image: bmonte91/python-todo
---
apiVersion: v1
kind: Service
metadata:
  name: python-docker-test-1
  namespace: default
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-test
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix  
        backend:
          service:
            name: python-docker-test-1
            port:
              number: 8080